Dockerfile
build.gradle.kts

also update build.gradle.kts not to create plain.jar
Fixed #5

chore: add Dockerfile

---

build.gradle.kts

fix: build.gradle.kts grammar error

---

.gitignore
buildSrc/src/main/kotlin/Dependencies.kt
buildSrc/src/main/kotlin/DependencyVersions.kt
user-infrastructure/build.gradle.kts
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/configuration/datasource/QueryBuilderConfig.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/User.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/repository/UserRepository.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/repository/UserRepositoryImpl.kt
user-infrastructure/src/main/resources/META-INF/persistence.xml
user-infrastructure/src/main/resources/application.yml
user-infrastructure/src/test/kotlin/com/xquare/v1userservice/EmbeddedMySQLConfiguration.kt
user-infrastructure/src/test/kotlin/com/xquare/v1userservice/EqualsTestUtil.kt
user-infrastructure/src/test/kotlin/com/xquare/v1userservice/domain/UserEntityTest.kt
user-infrastructure/src/test/kotlin/com/xquare/v1userservice/domain/repository/UserRepositoryTest.kt
user-infrastructure/src/test/resources/application.yml

fix: database connection error

---

build.gradle.kts
buildSrc/src/main/kotlin/Dependencies.kt
buildSrc/src/main/kotlin/DependencyVersions.kt
buildSrc/src/main/kotlin/PluginVersions.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/annotations/Aggregate.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/annotations/DomainService.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/annotations/Repository.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/annotations/Stub.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/User.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/saveuser/CreateSaveUserService.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/saveuser/SaveUserApi.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/spi/UserRepositorySpi.kt
user-infrastructure/build.gradle.kts
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/configuration/security/SecurityConfig.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/UserConfiguration.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/UserEntity.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/handler/UserHandler.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/mapper/UserDomainMapper.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/repository/UserRepositoryImpl.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserRouter.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/dto/saveuser/CreateUserRequest.kt
user-infrastructure/src/main/resources/META-INF/persistence.xml
user-infrastructure/src/test/kotlin/com/xquare/v1userservice/domain/UserEntityEntityTest.kt
user-infrastructure/src/test/kotlin/com/xquare/v1userservice/domain/repository/UserEntityRepositoryTest.kt

feat: add create User

---

.editorconfig
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/configuration/validate/BadRequestException.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/configuration/validate/RequestBodyValidator.kt

feat: add custom validator and exception

---

user-domain/src/main/kotlin/com/xquare/v1userservice/user/User.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/UserState.kt
user-domain/src/test/kotlin/com/xquare/v1userservice/user/UserTest.kt
user-domain/src/test/kotlin/com/xquare/v1userservice/user/UserUtils.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/UserEntity.kt
user-infrastructure/src/test/kotlin/com/xquare/v1userservice/domain/UserEntityTest.kt

feat: update UserEntity and User Domain Object

---

user-infrastructure/src/main/kotlin/com/xquare/v1userservice/configuration/cdc/DebeziumMessage.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/configuration/kafka/KafkaConfiguration.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/event/usercreate/UserCreatedEvent.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/handler/UserEventHandler.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/handler/UserExceptionEventHandler.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/handler/UserHandler.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/repository/UserRepositoryImpl.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserEventRouter.kt
user-infrastructure/src/main/resources/application.yml

fix: error when consuming AuthorityCreatedEvent from authentication service

---

debezium-setting.http

chore: add debezium-setting.http

---

user-domain/src/main/kotlin/com/xquare/v1userservice/user/User.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/dtos/SignInDomainRequest.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/impl/UserSignInApiImpl.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserHandler.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/dto/SignInRequest.kt
user-infrastructure/src/test/kotlin/com/xquare/v1userservice/user/router/UserRouterTest.kt

feat: add device token save logic

---

.github/workflows/prod-build.yaml

chore: add prod-build

---

user-domain/src/main/kotlin/com/xquare/v1userservice/stubs/InMemoryUserRepository.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/GetUserDeviceTokensApi.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/dtos/UserDeviceTokenResponse.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/impl/GetUserDeviceTokensApiImpl.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/spi/UserRepositorySpi.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/repository/UserRepositoryImpl.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserHandler.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserRouter.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/dto/GetUserDeviceTokenListResponse.kt

feat: add GetUserDeviceTokenList API

---

user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/UserSignInApi.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/dtos/TokenRefreshResponse.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/impl/UserSignInApiImpl.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/refreshtoken/exceptions/InvalidRefreshTokenException.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/refreshtoken/exceptions/RefreshTokenNotFoundException.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/refreshtoken/spi/RefreshTokenSpi.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/refreshtoken/exceptions/RefreshTokenSaveFailedException.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/refreshtoken/spi/RefreshTokenSpiImpl.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserHandler.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserRouter.kt

feat: add token refresh API

---

user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/impl/UserSignInApiImpl.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/jwt/JwtToken.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/verificationcode/VerificationCodeEntity.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/verificationcode/mapper/VerificationCodeMapper.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/verificationcode/spi/VerificationCodeSpiImpl.kt

fix: SignIn Error

---

user-infrastructure/src/main/resources/application.yml

chore: add Redis config

---

user-infrastructure/src/main/kotlin/com/xquare/v1userservice/configuration/exception/RequestHandlerNotFoundException.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/configuration/exception/handler/ErrorWebExchangeHandler.kt

feat: add NotFoundException Handler

---

user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/impl/CreateUserApiImpl.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/exceptions/UserAlreadyExistsException.kt

feat: check duplicate account Id

---

user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/CreateUserInPendingStateCompensator.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/impl/CreateUserApiImpl.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/impl/CreateUserInPendingStateImpl.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/spi/SaveUserBaseApplicationCompensator.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/spi/SaveUserBaseApplicationProcessor.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/spi/SaveUserBaseAuthorityCompensator.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/spi/SaveUserBaseAuthorityProcessor.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/utils/launchAndCatch.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/configuration/security/SecurityConfig.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/spi/SaveUserBaseApplicationSpiImpl.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/spi/SaveUserBaseAuthoritySpiImpl.kt

feat: 보상 트랜잭션 로직 추가

---

user-domain/src/main/kotlin/com/xquare/v1userservice/jwt/UnAuthorizedException.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserHandler.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserRouter.kt

feat: 포인트 조회할 때 헤더에서 UserId 조회해오도록 변경

---

user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/UserApi.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/impl/UserApiImpl.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserHandler.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserRouter.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/dto/GetUserListResponse.kt

feat: 사용자 조회 API 추가

---

user-domain/src/main/kotlin/com/xquare/v1userservice/user/User.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/UserApi.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/impl/UserApiImpl.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserHandler.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserRouter.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/dto/UpdateProfileFileRequest.kt

feat: 사용자 프로필 수정 API 추가

---

user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserHandler.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserRouter.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/dto/GetUserProfileResponse.kt

feat: 사용자 프로필 조회 API 추가

---

user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/impl/UserApiImpl.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/UserEntity.kt

feat: role enum으로 변경 & 회원가입 시 중복 가입 처리

---

user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/impl/UserApiImpl.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/spi/PointSpi.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/repository/UserRepositoryImpl.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserHandler.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/spi/PointSpiImpl.kt

🔀 :: (#101) 유저 생성시 PointStatus 테이블 생성

---

user-domain/src/main/kotlin/com/xquare/v1userservice/stubs/InMemoryUserRepository.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/UserApi.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/impl/UserApiImpl.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/spi/UserRepositorySpi.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/repository/UserRepositoryImpl.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserHandler.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserRouter.kt

🔀 :: (#103) 전체 학생 반환하기

---

user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/dtos/TokenResponse.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/impl/UserApiImpl.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserHandler.kt

feat: 유저 로그인 & 토큰 재발급 API Role 추가

---

user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/impl/UserApiImpl.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/spi/SaveUserTestAuthorityProcessor.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/spi/SaveUserTestAuthoritySpiImpl.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/spi/dtos/SaveUserTestAuthorityRequest.kt

🔀 :: (#107) 회원가입 시 Test계정일 경우 Test Authority 추가

---

user-domain/src/main/kotlin/com/xquare/v1userservice/stubs/InMemoryUserRepository.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/UserApi.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/impl/UserApiImpl.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/spi/UserRepositorySpi.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/repository/UserRepositoryImpl.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserHandler.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserRouter.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/dto/GetUserNameListResponse.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/dto/GetUserNameResponse.kt

close #109 
픽에 있는 유저 검색을 위해 만들었습니다.

🔀 :: (#109) name을 입력받아 유저 검색하기 api 

---

user-domain/src/main/kotlin/com/xquare/v1userservice/stubs/InMemoryUserRepository.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/UserApi.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/impl/UserApiImpl.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/spi/UserRepositorySpi.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/repository/UserRepositoryImpl.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserHandler.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserRouter.kt

close #111 
지금 현재 권한별로 student, teacher를 가져오는 API가 존재하는데 전체를 가져올 경우가 필요하여 이 API를 만들게 되었습니다.
student, teacher만 가지고 오는 API는 이 API가 머지되고 프론트와 백엔드 쪽에서 다 바꾸면 그때 지우도록 하겠습니다.

feat: 권한으로 유저 조회 API

---

user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserHandler.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserRouter.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/dto/GetUserInfoRequest.kt

merge :: (#114)  HTTP line is larger than 4096 bytes에러 

---

user-domain/src/main/kotlin/com/xquare/v1userservice/stubs/InMemoryUserRepository.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/impl/UserApiImpl.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/repository/UserRepositoryImpl.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserRouter.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/dto/CreateUserRequest.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/spi/SaveUserTestAuthoritySpiImpl.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/spi/dtos/SaveUserTestAuthorityRequest.kt

URL이 명세와 달라 명세대로 변경 하였습니다
* https://linear.app/team-xquare/issue/XQU-17/user-devicetoken-가져오기-api-error

🔀 :: (#17) DeviceToken 가져오기 api Error

---

user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/dto/UpdateProfileFileRequest.kt

유저 프로필을 등록하는 API에 허용된 확장자만 등록 가능하도록 변경하였습니다

⚡️:: @field:Pattern 추가

---

user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserHandler.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/dto/GetExcludeUserIdListRequest.kt

param으로 요청 보내는 것에서 body로 받는 것으로 수정하였습니다

🔀 :: (#81) 4096 bytes Error 해결

---

user-infrastructure/src/main/kotlin/com/xquare/v1userservice/jwt/JwtToken.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/jwt/JwtTokenGenerator.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/spi/JwtTokenGeneratorSpiImpl.kt

close #134 
토큰 만료 시간이 access든 refresh든 같은 access 만료 시간을 가져오는 로직을 타입에 따라 만료시간을 다르게 하였습니다

🔀 :: (#134) RefreshToken 만료 시간 수정

---

user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserHandler.kt

클라의 요청으로 profile이 null일 경우 "" 보내도록하였습니다

🔀 :: (#248) null일 경우 ""으로 변환

---

user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/UserApi.kt
user-domain/src/main/kotlin/com/xquare/v1userservice/user/api/impl/UserApiImpl.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserHandler.kt
user-infrastructure/src/main/kotlin/com/xquare/v1userservice/user/router/UserRouter.kt

로그아웃해도 알림이 가는 버그를 해결하기 위해 로그아웃 API를 만들었습니다
- logout API 요청 시, deviceToken를 ""로 변환

🔀 :: (#243) logout API
